import esbuild from "esbuild";
import { builtinModules } from "module";

const production = process.argv[2] === "production";

await esbuild.build({
  banner: {
    js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */"
  },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((mod) => `node:${mod}`)
  ],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: "main.js",
  platform: "node",
  sourcemap: production ? false : "inline",
  target: "es2018",
  treeShaking: true
});
